# ==============================================================================
# S e r v e r
# ==============================================================================
#[server]
#port = 3000

# ==============================================================================
# D a t e n b a n k
# ==============================================================================
[db]
populate = true

# ==============================================================================
# L o g g i n g
# ==============================================================================
[log]
#dir = "/tmp"
# Auskommentieren fuer Lasttests
level = "debug"
pretty = true
